### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hygorrasec** [gunzino/tibia11-nodejs-parser#1]
Look: https://image.prntscr.com/image/q-c_0H98TruZTzrOWzyIwQ.jpeg

`$ node parser.js appearances.dat >> Decoding appearances.dat (node:16588) UnhandledPromiseRejectionWarning: Error: invalid wire type 6 at offset 99 at BufferReader.Reader.skipType (C:\Program Files\Git\tibia11-nodejs-parser\node_modules\protobufjs\src\reader.js:375:19) at Type.Appearance$decode [as decode] (eval at Codegen (C:\Program Files\Git\tibia11-nodejs-parser\node_modules\@protobufjs\codegen\index.j
s:50:33), <anonymous>:22:5) at Type.Appearances$decode [as decode] (eval at Codegen (C:\Program Files\Git\tibia11-nodejs-parser\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:23:26) at Type.decode_setup [as decode] (C:\Program Files\Git\tibia11-nodejs-parser\node_modules\protobufjs\src\type.js:507:25) at Appearances.loadFile (C:\Program Files\Git\tibia11-nodejs-parser\src\Appearances.js:21:32) at <anonymous> (node:16588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:16588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by gunzino** [comment]
Hello!

What node.js version are you using ? Also the appearances.proto may be outdated, I am going to update it now

**Comment by gunzino** [comment]
Can you try that now ?
